# Generated by Django 4.2.5 on 2023-10-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Marque')),
                ('model_car', models.CharField(max_length=255, verbose_name='Model')),
                ('phone_number', models.CharField(blank=True, default='+213779675028', max_length=255, verbose_name='Téléphone')),
                ('year', models.IntegerField(default=2000, verbose_name='Année')),
                ('boite', models.CharField(choices=[('au', 'Automatique'), ('ma', 'Manuel')], default='ma', max_length=255, verbose_name='Boite de vitesse')),
                ('energy', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('gpl', 'GPL')], default='essence', max_length=255, verbose_name='Energie')),
                ('description', models.TextField(blank=True, default=None, max_length=1024, verbose_name='Description')),
                ('color', models.CharField(blank=True, default=None, max_length=255, verbose_name='Coleur')),
                ('horse_power', models.CharField(blank=True, default=None, max_length=255, verbose_name='Puissance')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=16, verbose_name='Prix')),
            ],
        ),
    ]
